name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Dependencies and Build
        run: make install
      - name: Format Check
        run: make format
      - name: Lint Code
        run: make lint
      - name: Run Tests
        run: make test
      - name: Build Project
        run: make build
      - name: Run Project
        run: make run
