name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Project
        run: |
          cd data_processing
          make build
      - name: Format Check
        run: |
          cd data_processing
          make format
      - name: Lint Code
        run: |
          cd data_processing
          make lint
      - name: Run Tests
        run: |
          cd data_processing
          make test
      - name: Run Project
        run: |
          cd data_processing
          make run
